# Generated by Django 6.1.1 on 2026-09-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('men', 'For Men'), ('women', 'For Women'), ('oud', 'Oud'), ('gift', 'Gift Sets')], max_length=10)),
                ('description', models.TextField(help_text='Shown on the product card')),
                ('notes', models.CharField(blank=True, help_text="Comma-separated scent notes, e.g. 'woody, amber, spice'. Used by the AI search to match intent even when the exact word isn't in the description.", max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.CharField(help_text='Path used by the frontend, e.g. image/him/d8.jpg', max_length=255)),
                ('is_bestseller', models.BooleanField(default=False, help_text="Shown in the homepage 'Best Sellers' section when checked.")),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
