# Generated by Django 4.2.30 on 2026-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text="Shown in the homepage 'Best Sellers' section when checked."),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notes',
            field=models.CharField(blank=True, help_text="Comma-separated scent notes, e.g. 'woody, amber, spice'.", max_length=255),
        ),
    ]
