# Generated by Django 4.2.30 on 2026-09-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_perfume_is_bestseller_alter_perfume_notes'),
        ('perfumes', '0002_review'),
    ]

    operations = [
    ]
