# Generated by Django 6.1.1 on 2026-09-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_checkout_session_id',
        ),
    ]
